// src/components/HeaderThemeSwitch.vue
<template>
  <label class="swap swap-rotate btn btn-ghost">
    <!-- this hidden checkbox controls the state -->
    <input type="checkbox" class="theme-controller" value="dark">

    <!-- sun icon -->
    <Icon name="heroicons:sun" class="swap-off size-5 fill-current" />

    <!-- moon icon -->
    <Icon name="heroicons:moon" class="swap-on size-5 fill-current" />
  </label>
</template>

// components/HeaderThemeSwitch.tsx
import { Icon } from "@iconify/react";

export default function HeaderThemeSwitch() {
  return (
    <label className="swap swap-rotate btn btn-ghost">
      <input type="checkbox" className="theme-controller" value="dark" />
      <Icon icon="heroicons:sun" className="swap-off size-5 fill-current" />
      <Icon icon="heroicons:moon" className="swap-on size-5 fill-current" />
    </label>
  )
}
