// src/components/HeaderNavHorizontal.vue
<script setup lang="ts">
defineProps<{nav: {
    url: string;
    label?: string | undefined;
    icon?: string | undefined;
}[]}>();
</script>

<template>
  <nav
    class="max-sm:hidden flex not-odd:flex-none max-sm:absolute right-4 z-1 max-sm:border-[1px] max-sm:border-neutral">
    <ul v-if="nav" class="menu menu-horizontal max-sm:menu-vertical">
      <HeaderLink v-for="item in nav" :key="item.url" :url="item.url!">
        <Icon v-if="item.icon" :name="item.icon" />
        <span v-if="item.label">{{ item.label }}</span>
      </HeaderLink>
    </ul>
  </nav>
</template>

// components/HeaderNavHorizontal.tsx
import { Icon } from "@iconify/react"
import HeaderLinkComponent from "./HeaderLink"
import { type Link } from "@/sanity.types"

export default async function HeaderNavHorizontal({ links }: { links: Link[] }) {

  return (
    <nav
      className="max-md:hidden flex not-odd:flex-none max-sm:absolute right-4 z-1 max-sm:border-[1px] max-sm:border-neutral">
      <ul className="menu menu-horizontal max-sm:menu-vertical">
        {links.map((link) => {
          return (
            <HeaderLinkComponent key={link._id} {...link} >
              {link.icon && link.icon.name && <Icon icon={link.icon.name} />}
              {link.title}
            </HeaderLinkComponent>
          )
        })}
      </ul>
    </nav >
  )
}
