// components/HeaderNavVertical.tsx
import { Icon } from "@iconify/react";
import HeaderLinkComponent from "./HeaderLink";
import { type Link } from "@/sanity.types";

export default async function HeaderNavVertical({ links }: { links: Link[] }) {
  return (
    <details className="md:hidden">
      <summary className="btn btn-ghost">
        <Icon icon="heroicons:bars-3-solid" className="size-5" />
      </summary>
      <nav className="flex not-odd:flex-none absolute right-4 bg-base-100 z-10 border-[1px] border-neutral">
        <ul className="menu menu-vertical">
          {links.map((link) => {
            return (
              <HeaderLinkComponent key={link._id} {...link}>
                {link.icon && link.icon.name && <Icon icon={link.icon.name} />}
                {link.title}
              </HeaderLinkComponent>
            );
          })}
        </ul>
      </nav>
    </details>
  );
}

// src/components/HeaderNavVertical.vue
<script setup lang="ts">
defineProps<{nav: {
    url: string;
    label?: string | undefined;
    icon?: string | undefined;
}[]}>();
</script>

<template>
  <details>
    <summary class="max-sm:btn hidden btn-ghost">
      <Icon name="i-heroicons:bars-3-solid" class="size-5" />
    </summary>
    <nav
      class="flex not-odd:flex-none max-sm:absolute right-4 bg-base-100 z-1 max-sm:border-[1px] max-sm:border-neutral">
      <ul v-if="nav" class="menu max-sm:menu-vertical">
        <HeaderLink v-for="item in nav" :key="item.url" :url="item.url!">
          <Icon v-if="item.icon" :name="item.icon" />
          <span v-if="item.label">{{ item.label }}</span>
        </HeaderLink>
      </ul>
    </nav>
  </details>
</template>
