// components/Header.tsx
import Link from "next/link";
import HeaderThemeSwitch from "./HeaderThemeSwitch";
import { GET_CONFIG_QUERYResult } from "@/sanity.types";
import HeaderNavHorizontal from "./HeaderNavHorizontal";
import { imageURL } from "@/lib/imageURL";
import Image from "next/image";
import HeaderNavVertical from "./HeaderNavVertical";
import Search from "./Search";

async function Header({ config }: { config: NonNullable<GET_CONFIG_QUERYResult> }) {
  // Transform headerLinks to convert null icons to undefined
  const headerLinks = (config?.headerLinks || []).map(link => ({
    ...link,
    icon: link.icon ?? undefined
  }));

  return (
    <header className="navbar bg-base-100/30 backdrop-blur-lg font-mono border-b-base-content border-b sticky top-0 z-50">
      <a href="#content" className="sr-only focus:not-sr-only">Skip to main content</a>
      <div className="flex flex-row items-center flex-1">
        <div className="flex-1">
          <Link className="btn btn-ghost text-xl" href="/">
            {config?.title && (<span>{config.title}</span>)}
            {config?.headerLogo && (
              <Image src={imageURL(config.headerLogo).url()} alt={config.headerLogoAlt || config.title || 'Header Logo'} width={100} height={100} />
            )}
          </Link>
        </div>
        {/* <HeaderLangSwitch /> */}
        <HeaderThemeSwitch />
        <Search />
        <HeaderNavVertical links={headerLinks} />
        <HeaderNavHorizontal links={headerLinks} />
      </div>
    </header >
  )
}

export default Header

// src/components/Header.vue
<script setup lang="ts">
import HeaderThemeSwitch from './HeaderThemeSwitch.vue'
const { locale } = useI18n();
const { data: link } = await useAsyncData('header', (ctx) => {
  return queryCollection('header')
    .select(locale.value)
    .first();
}, {
  watch: [locale],
});

</script>

<script lang="ts">
export default {
  name: 'AppHeader'
}
</script>
<template>
  <header class="navbar bg-base-100/30 backdrop-blur-lg font-mono border-b-neutral border-b-[1px] fixed z-50">
    <div class="flex flex-row flex-1">
      <div class="flex-1">
        <NuxtLink v-if="link" class="btn btn-ghost text-xl" :href="`/`">{{ link[locale].title }}</NuxtLink>
      </div>
      <HeaderLangSwitch />
      <HeaderThemeSwitch />
    </div>
    <HeaderNavVertical v-if="link" :nav="link[locale].nav" />
    <HeaderNavHorizontal v-if="link" :nav="link[locale].nav" />
  </header>
  <header class="navbar invisible">
    <div class="flex flex-row flex-1">
      <div class="flex-1">
        <NuxtLink v-if="link" class="btn btn-ghost text-xl" :href="`/`">{{ link[locale].title }}</NuxtLink>
      </div>
    </div>
  </header>
</template>
