// components/HeaderLink.tsx
import { type Link as HeaderLink } from "@/sanity.types"
import Link from "next/link";

type HeaderLinkProps = HeaderLink & { children: React.ReactNode };

export default function HeaderLink({ url, slug, children }: HeaderLinkProps) {
  if(slug && slug.current) {
    return (
      <li>
        <Link href={`/${slug.current}`} className="link no-underline">
          \ {children}
        </Link>
      </li>
    )
  }

  if(url && url.startsWith('https')) {
    return (
      <li>
        <Link href={url} className="link no-underline">
          \ {children}
        </Link>
      </li>
    )
  }

  return null;
}

// src/components/HeaderLink.vue
<script setup lang="ts">
const props = defineProps<{
  url: string,
}>();

const { locale } = useI18n();

</script>
<template>
  <li>
    <NuxtLink v-if="!props.url.startsWith('https')" :to="`/${locale}${props.url}`" class="link no-underline">
      \
      <slot />
    </NuxtLink>
    <NuxtLink v-if="props.url.startsWith('https')" :to="props.url" class="link no-underline">
      \
      <slot />
    </NuxtLink>
  </li>
</template>
